export const TYPES = {
  INSERTANDO_VALOR: "INSERTANDO_VALOR",
  COLOCANDDO_PUNTO: "COLOCANDO_PUNTO",
  DELET_NUMBER: "DELETE_NUMBER",
  RESET: "RESET",
  OPERATION: "OPERATION",
  EQUAL: "EQUAL",
};
